# Generated by Django 3.2.6 on 2021-10-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.CharField(default='Default', max_length=200),
        ),
    ]
