# Generated by Django 3.2.6 on 2021-10-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='hero',
            new_name='book',
        ),
    ]
